# Generated by Django 2.2.4 on 2019-08-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('nic', models.CharField(max_length=16, unique=True)),
                ('image', models.ImageField(upload_to='documents/%Y/%M/%d/')),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Basic_info',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.IntegerField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Degree',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_type', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EmployeeType',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'JobTitle',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=3)),
                ('blood_group', models.CharField(max_length=10)),
                ('other_mobile', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(null=True)),
                ('permanent_address', models.CharField(max_length=50)),
                ('present_address', models.CharField(max_length=10)),
                ('maretial_status', models.CharField(max_length=1)),
                ('age', models.FloatField()),
                ('wedding_date', models.DateField()),
                ('spouse_name', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=500)),
                ('relieving_date', models.DateField()),
                ('tags', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'personal_details',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='SourceOfHire',
            fields=[
                ('source_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SourceOfHire',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('previous_company', models.CharField(max_length=50)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.JobTitle')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_of_Joining', models.DateField()),
                ('PAN_number', models.CharField(max_length=10, unique=True)),
                ('employee_Status', models.BooleanField()),
                ('apprisal_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info_apprisal_manager', to='HRMS_App.BasicInfo')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.Department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.Designation')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.BasicInfo')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.EmployeeType')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.Location')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='HRMS_App.BasicInfo')),
                ('reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info_reported_by', to='HRMS_App.BasicInfo')),
                ('seating_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='HRMS_App.Location')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.SourceOfHire')),
            ],
            options={
                'db_table': 'work_details',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_description', models.CharField(max_length=300)),
                ('about_me', models.CharField(max_length=300)),
                ('expertise', models.CharField(max_length=300)),
                ('emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.BasicInfo')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
                ('date_of_completion', models.DateField()),
                ('additional_notes', models.CharField(max_length=50)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.Degree')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.BasicInfo')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('dependant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True)),
                ('emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS_App.BasicInfo')),
            ],
            options={
                'db_table': 'dependant',
            },
        ),
    ]
