# Generated by Django 2.1 on 2019-08-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='maretial_status',
            new_name='marital_status',
        ),
        migrations.RemoveField(
            model_name='workdetails',
            name='apprisal_manager',
        ),
        migrations.AddField(
            model_name='workdetails',
            name='appraisal_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_manager', to='HRMS_App.BasicInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nic',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='degree',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='modified_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='modified_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sourceofhire',
            name='modified_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
