# Generated by Django 2.1 on 2019-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_App', '0002_auto_20190830_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
