# Generated by Django 2.1 on 2019-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_App', '0003_auto_20190830_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='emp_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
